FROM jenkins/agent:latest-alpine-jdk11

ARG OC_VERSION=4.10
USER root
WORKDIR /

<%= snippet('labels', binding) -%>

COPY banner.txt /etc/motd
COPY 99-zmotd.sh /docker-entrypoint.d/

RUN apk add --no-cache \
  tzdata \
  libcap \
  vault \
  ruby \
  python3 \
  py3-pip \
  jq \
  openldap-clients \
  curl \
  wget \
  coreutils \
  zip \
  whois \
  gcompat \
  bind-tools \
  && setcap -r /usr/sbin/vault

RUN apk add --no-cache \
  minio-client --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community

RUN curl -sLo /tmp/oc.tar.gz https://mirror.openshift.com/pub/openshift-v$(echo $OC_VERSION | cut -d'.' -f 1)/clients/ocp/stable-$OC_VERSION/openshift-client-linux.tar.gz && \
    tar xzvf /tmp/oc.tar.gz -C /usr/local/bin/ && \
    rm -rf /tmp/oc.tar.gz

<%= snippet('docker-entrypoint', binding) -%>

<%= snippet('tini', binding) -%>

USER jenkins
WORKDIR /home/jenkins
ENV TZ=America/Vancouver

<% if image.variant == 'dind' -%>

COPY 50-start-dockerd.sh /docker-entrypoint.d/
USER root
RUN apk add --no-cache \
  docker \
  && unset DOCKER_HOST

<% end -%>

<% if image.variant == 'javadev' -%>

USER root
RUN apk add --no-cache \
  openjdk8

WORKDIR /src
ADD https://s3.tis.bcit.ca/dist/java/apache-maven-3.9.4-bin.tar.gz .
ADD https://s3.tis.bcit.ca/dist/java/grails-2.5.6.zip .
ADD https://s3.tis.bcit.ca/dist/java/grails-3.2.3.zip .
RUN ln -s /usr/lib/jvm/java-1.8-openjdk /opt/java/openjdk8 \
  && tar xzvf apache-maven-3.9.4-bin.tar.gz -C /opt \
  && unzip grails-2.5.6.zip -d /opt \
  && unzip grails-3.2.3.zip -d /opt \
  && rm -f /src/*

USER jenkins
<% end -%>

ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]

CMD ["jshell"]
