FROM jenkins/agent:latest-alpine-jdk11

USER root
WORKDIR /

<%= snippet('labels', binding) -%>

COPY banner.txt /etc/motd
COPY 99-zmotd.sh /docker-entrypoint.d/

RUN apk add --no-cache \
  tzdata \
  libcap \
  vault \
  ruby \
  python3 \
  py3-pip \
  jq \
  openldap-clients \
  curl \
  wget \
  coreutils \
  && setcap -r /usr/sbin/vault

<%= snippet('docker-entrypoint', binding) -%>

<%= snippet('tini', binding) -%>

USER jenkins
WORKDIR /home/jenkins
ENV TZ=America/Vancouver

<% if image.variant == 'dind' -%>

COPY 50-start-dockerd.sh /docker-entrypoint.d/
USER root
RUN apk add --no-cache \
  docker \
  && unset DOCKER_HOST

<% end -%>

ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]

CMD ["jshell"]
